name: XUnit Tests
on: [push, pull_request, release]
jobs:
  RunTests:
    name: Runs XUnit Tests
    runs-on: ubuntu-latest
    steps:
        # Display the event that triggered the workflow
        - run: echo "The job was triggered by a ${{github.event_name}} event"
  
        # Runner information
        - run: echo "This job is now running on a ${{runner.os}} server hosted by GitHub"
  
        # Information about the repository and branch
        - run: echo "The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}."
        
        # Use Actions located in https://github.com/actions
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
        - name: Build
          run: dotnet build
        - name: Test
          run: dotnet test