name: XUnit Tests
on: [push, pull_request, release]
jobs:
  RunTests:
    name: Runs XUnit Tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
        - name: Build
          run: dotnet build
        - name: Test
          run: dotnet test